// react-basic/src/adv/01-router/Movie.jsx
import React, { Component } from 'react'
import { Link, Route, Switch } from 'react-router-dom'

const Hot = () => {
  return <h2>正在热映</h2>
}

const Coming = () => {
  return <h2>即将上映</h2>
}

export default class Movie extends Component {
  render() {
    return (
      <div>
        <h1>Movie</h1>
        {/* <Link to='/coming'>即将上映</Link>
        <Link to='/hot'>正在热映</Link>
        <Switch> 
          <Route path='/hot'>
            <Hot></Hot>
          </Route>
          <Route path='/coming'>
            <Coming></Coming>
          </Route>
          <Route path='/index'>
            <Hot></Hot>
          </Route>
        </Switch> */}
      </div>
    )
  }
}

// maoyan/src/views/movie/Movie.vue
<template>
  <div>
    <router-link to="/city">城市</router-link>
    <router-link to="/index/movie/hotshowing">正在热映</router-link>
    <router-link to="/index/movie/comingsoon">即将上映</router-link>
    <router-link to="/search">搜索</router-link>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Movie"
};
</script>
